version: "3"
services:
  server-1:
    image: openjdk:11.0-jdk-stretch
    command: ./server.sh
    working_dir: /usr/local/src/app
    environment:
      - SERVER_PORT=8080
      - EUREKA_SERVICE_URL=http://server-1:8080/eureka/,http://server-2:8081/eureka/
    volumes:
      - ./:/usr/local/src/app
    ports:
      - 8080:8080
      - 28080
  server-2:
    image: openjdk:11.0-jdk-stretch
    command: ./server.sh
    working_dir: /usr/local/src/app
    environment:
      - SERVER_PORT=8081
      - EUREKA_SERVICE_URL=http://server-1:8080/eureka/,http://server-2:8081/eureka/
    volumes:
      - ./:/usr/local/src/app
    ports:
      - 8081:8081
      - 28080
  client-1:
    image: openjdk:11.0-jdk-stretch
    command: ./client.sh
    working_dir: /usr/local/src/app
    environment:
      - SERVER_PORT=8082
      - EUREKA_SERVICE_URL=http://server-1:8080/eureka/
    volumes:
      - ./:/usr/local/src/app
    ports:
      - 8082:8082
      - 28080
    depends_on:
      - server-1
      - server-2
  client-2:
    image: openjdk:11.0-jdk-stretch
    command: ./client.sh
    working_dir: /usr/local/src/app
    environment:
      - SERVER_PORT=8083
      - EUREKA_SERVICE_URL=http://server-1:8080/eureka/
    volumes:
      - ./:/usr/local/src/app
    ports:
      - 8083:8083
      - 28080
    depends_on:
      - server-1
      - server-2
  client-3:
    image: openjdk:11.0-jdk-stretch
    command: ./client.sh
    working_dir: /usr/local/src/app
    environment:
      - SERVER_PORT=8084
      - EUREKA_SERVICE_URL=http://server-1:8080/eureka/
    volumes:
      - ./:/usr/local/src/app
    ports:
      - 8084:8084
      - 28080
    depends_on:
      - server-1
      - server-2
