global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "component"
    scrape_interval: 10s
    metrics_path: /management/prometheus
    consul_sd_configs:
      - server: "server-1:8080"
    relabel_configs:
      - source_labels: ["__meta_consul_service"]
        target_label: service
      - source_labels: ["__meta_consul_service_metadata_environment"]
        target_label: environment
      - source_labels: ["__meta_consul_service_metadata_group"]
        target_label: group
      - source_labels: ["__meta_consul_tags"]
        action: keep
      - source_labels: ["__meta_consul_service"]
        target_label: job