spring:
  application:
    name: client

server:
  port: 8080

management:
  server:
    port: 28080
  endpoints:
    web:
      base-path: /management
      exposure:
        include: *

eureka:
  instance:
    hostname: localhost
    app-group-name: eureka
    status-page-url-path: /management/prometheus
    health-check-url-path: /management/health
    metadata-map:
      environment: local